### ISSUE TITLE
Last push before deadline

### ISSUE THREAD

**Issue by NearHuscarl** [NearHuscarl/EDictionary#72]
### Design
* [x] Style combobox d2db9c80c1df0d1b428a08994d73745408ed8484
* [x] Style tabcontrol
* [x] ~Ẩn con trỏ sau khi trong textbox chọn key shortcut (settings -> dynamic)~ bỏ shortcut textbox ở commit 3a38b22455f62f3ea474b195cdf78505f04f9d5b
* [x] Ẩn đường viền đứt đoạn (bấm alt sẽ xuất hiện) trong tất cả các control 0fd65c0
![image](https://user-images.githubusercontent.com/23303775/41280460-31938018-6e59-11e8-8c60-a1789220bcb5.png) 

* [x] #60 Thay selection color sang cyan 0fd65c0cc432b5d5c9ba00f18be020ff68ea3f6a
![image](https://user-images.githubusercontent.com/23303775/41280605-88489d76-6e59-11e8-987a-507114378903.png)
* [x] #60 Đổi màu con trỏ trong updowninterger sang cyan 0fd65c0cc432b5d5c9ba00f18be020ff68ea3f6a
* [x] background button đổi màu dần (dùng animation) khi hơ chuột lên
* [x] Trim input at n chars
* [x] Logo
* [ ] Custom Mouse texture
* [x] Apply button style
   * [ ] Enable/Disable
   * [x] Run color animation when mouse enter
   * [x] Disable after pressing
   * [x] Enable again after change something in settings

### Feature
* [x] #69 EDictictionary Dynamic
* [x] Nút thêm từ vào danh sách từ học bên cạnh 2 nút lịch sử (không cần phải vào settings)
* [ ] Mở học từ từ cửa sổ main
* [x] Tooltip
* [ ] Nút export từ ra màn hình (rtf, pdf..)

### Bugs
* [ ] 2 icon trong menutray bị mất sau khi mở EDictionary từ tray lên
* [x] Check danh sách học từ có nằm trong từ điển hay không trước khi nạp
* [x] #64 Kéo thả title bar không được ở vị trí gần nút tắt trong cửa sổ settings 75476e8

### Misc
* [x] Remove watcher

**Ai làm phần nào thì comment trước**
